# Generated by Django 3.2.23 on 2025-01-11 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('educational', 'Educativo'), ('marketing', 'Marketing'), ('social', 'Redes Sociales'), ('business', 'Negocios'), ('personal', 'Personal')], max_length=20, verbose_name='Categoría')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=20, verbose_name='Nivel de Dificultad')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Imagen de Vista Previa')),
                ('configuration', models.JSONField(default=dict, verbose_name='Configuración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Template de Video',
                'verbose_name_plural': 'Templates de Video',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('script', models.TextField(blank=True, verbose_name='Script')),
                ('base_media', models.FileField(blank=True, null=True, upload_to='project_media/', verbose_name='Medio Principal')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20, verbose_name='Estado')),
                ('notification_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para Notificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='video_app.videotemplate', verbose_name='Template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proyecto de Video',
                'verbose_name_plural': 'Proyectos de Video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.IntegerField(default=0, help_text='Progreso del procesamiento en porcentaje')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_tasks', to='video_app.videoproject')),
            ],
            options={
                'verbose_name': 'Tarea de Procesamiento',
                'verbose_name_plural': 'Tareas de Procesamiento',
                'ordering': ['-created_at'],
            },
        ),
    ]
