# Generated by Django 4.2.8 on 2025-01-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoproject",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="videoproject",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="output_video",
            field=models.FileField(
                blank=True, null=True, upload_to="generated_videos/"
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Borrador"),
                    ("processing", "Procesando"),
                    ("completed", "Completado"),
                    ("failed", "Fallido"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="video_app.videotemplate",
            ),
        ),
        migrations.CreateModel(
            name="VideoScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(help_text="Orden de la escena en el video"),
                ),
                ("duration", models.FloatField(help_text="Duración en segundos")),
                ("transition_in", models.CharField(blank=True, max_length=50)),
                ("transition_out", models.CharField(blank=True, max_length=50)),
                ("background_color", models.CharField(default="#000000", max_length=7)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="video_app.videoproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "order")},
            },
        ),
        migrations.CreateModel(
            name="VideoElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "element_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("shape", "Forma"),
                            ("audio", "Audio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Texto o ruta al archivo según el tipo"),
                ),
                ("position_x", models.FloatField(help_text="Posición X (0-1)")),
                ("position_y", models.FloatField(help_text="Posición Y (0-1)")),
                ("width", models.FloatField(help_text="Ancho relativo (0-1)")),
                ("height", models.FloatField(help_text="Alto relativo (0-1)")),
                ("rotation", models.FloatField(default=0)),
                ("opacity", models.FloatField(default=1.0)),
                ("z_index", models.IntegerField(default=0)),
                (
                    "effects",
                    models.JSONField(
                        default=dict, help_text="Efectos aplicados al elemento"
                    ),
                ),
                (
                    "scene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="video_app.videoscene",
                    ),
                ),
            ],
            options={
                "ordering": ["z_index"],
            },
        ),
    ]
