# Generated by Django 3.2.23 on 2025-01-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_alter_videoproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoelement',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='videoelement',
            old_name='rotation',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='videoelement',
            name='opacity',
        ),
        migrations.RemoveField(
            model_name='videoelement',
            name='z_index',
        ),
        migrations.AddField(
            model_name='videoelement',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoscene',
            name='transition_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videoscene',
            name='transition_type',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='effects',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='element_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('effect', 'Effect')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='height',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='videoscene',
            name='duration',
            field=models.FloatField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='videoscene',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='videoscene',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='transition_in',
        ),
        migrations.RemoveField(
            model_name='videoscene',
            name='transition_out',
        ),
    ]
