# Generated by Django 3.2.23 on 2025-01-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_auto_20250111_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('tts', 'Text to Speech'), ('upload', 'Uploaded Audio'), ('music', 'Background Music')], max_length=10)),
                ('content', models.FileField(blank=True, null=True, upload_to='audio_elements/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('voice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(default=1.0)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_elements', to='video_app.videoscene')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
